name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Create env file
        run: echo "${{ secrets.BLOG_ENV_PRODUCTION }}" > .env.production
      - name: Build the Docker image
        run: docker build --progress=plain -t jinchao68/blog:v0 .
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Push the Docker Image
        run: docker push jinchao68/blog:v0

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > test_key.pem
          chmod 600 test_key.pem
          ssh -i test_key.pem -o StrictHostKeyChecking=no -o ConnectTimeout=10 ${{ secrets.HOST_USERNAME }}@${{ secrets.HOST }} "echo SSH connection successful"
      - name: executing remote ssh commands using private key
        if: success()
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -x
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            docker pull jinchao68/blog:v0
            docker stop client-blog-v2 || true
            docker rm client-blog-v2 || true
            docker run -dp 8082:8082 --name client-blog-v2 --restart unless-stopped jinchao68/blog:v0
